# Generated by Django 4.1.4 on 2022-12-07 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Math',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op', models.CharField(choices=[('sum', 'sum'), ('sub', 'sub'), ('div', 'div'), ('mul', 'mul')], max_length=3, verbose_name='Operation')),
                ('a', models.IntegerField()),
                ('b', models.IntegerField()),
                ('result', models.FloatField()),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
